#!/bin/bash
#PBS -q workq 
#PBS -A loni_unconvrs21
#PBS -l nodes=1:ppn=48
#PBS -l walltime=60:00:00 
#PBS -o Verification1_Diffusion_Reference_x1024
#PBS -j oe
#PBS -N Verification1_Diffusion_Reference_x1024
#PBS -m e
#PBS -M ahass16@lsu.edu 

cd /scratch/ahass16/mrst-2020a
module load matlab/r2019b
matlab -nodisplay -nosplash -r startup
matlab -nodisplay -nosplash -r "addpath(genpath('/scratch/ahass16/mrst-2020a/modules/shale_chapter')); Verification1_Diffusion_Reference_x1024;" 

#matlab -nodisplay -nosplash -r "p = genpath('/scratch/ahass16/mrst-2019b/modules/pEDFM');" 
#matlab -nodisplay -nosplash -r "addpath(p);"
#matlab -nodisplay -nosplash -r SlotDrill_NF_EDFM_Hassan
