#!/bin/bash
#PBS -q workq 
#PBS -A loni_unconvrs20
#PBS -l nodes=1:ppn=48
#PBS -l walltime=72:00:00 
#PBS -o Semicircle_500microD_Gravity
#PBS -j oe
#PBS -N Semicircle_500microD_Gravity
#PBS -m e
#PBS -M ahass16@lsu.edu 

cd /scratch/ahass16/mrst-2020a
module load matlab/r2019b
matlab -nodisplay -nosplash -r startup
matlab -nodisplay -nosplash -r "addpath(genpath('/scratch/ahass16/mrst-2020a/modules/shale_chapter')); Semicircle_500microD_Gravity;" 

#matlab -nodisplay -nosplash -r "p = genpath('/scratch/ahass16/mrst-2019b/modules/pEDFM');" 
#matlab -nodisplay -nosplash -r "addpath(p);"
#matlab -nodisplay -nosplash -r SlotDrill_NF_EDFM_Hassan
