#!/bin/bash
#PBS -q single 
#PBS -A loni_unconvrs21
#PBS -l nodes=1:ppn=48
#PBS -l walltime=150:00:00 
#PBS -o Bakken_SDEOR_Primary_90NFs_Pwf_1000psia
#PBS -j oe
#PBS -N Bakken_SDEOR_Primary_90NFs_Pwf_1000psia
#PBS -m e
#PBS -M ahass16@lsu.edu 

cd /scratch/ahass16/mrst-2020a
module load matlab/r2019b
matlab -nodisplay -nosplash -r startup
matlab -nodisplay -nosplash -r "addpath(genpath('/scratch/ahass16/mrst-2020a/modules/shale_chapter')); Bakken_SDEOR_Primary_90NFs_Pwf_1000psia;" 

#matlab -nodisplay -nosplash -r "p = genpath('/scratch/ahass16/mrst-2019b/modules/pEDFM');" 
#matlab -nodisplay -nosplash -r "addpath(p);"
#matlab -nodisplay -nosplash -r SlotDrill_NF_EDFM_Hassan
